const ACTIONS = {
    LOGIN: 'LOGIN',
    GET_TOKEN: 'GET_TOKEN',
    GET_USER: 'GET_USER',
    GET_ALL_USERS: 'GET_ALL_USERS',
    CREATE_TACHE: 'CREATE_TACHE',
    UPDATE_TACHE: 'UPDATE_TACHE',
    DELETE_TACHE: 'DELETE_TACHE',
    FETCH_ALL: 'FETCH_ALL'
}

export default ACTIONS